name: Build newest deb package for aarch64 debian

#on:
#  push:
#    tags:
#      - "*"

on:
  push:
    branches:
      - "*"

jobs:
  indi:
    runs-on: ubuntu-24.04-arm

    container:
      image: debian:trixie

    steps:
      - name: uname
        run: uname -m

      - name: OS
        run: cat /etc/os-release

      - name: Reconfigure APT Repo sources
        run: "sed -i 's/Types: deb/Types: deb deb-src/' /etc/apt/sources.list.d/debian.sources"

      - name: Install Dependencies
        run: |
          apt update
          apt install -y git dpkg-dev devscripts equivs

      - name: Setup Build Env
        run: |
          mkdir /tmp/indi && cd /tmp/indi
          apt source indi
          git clone --depth 1 https://github.com/indilib/indi.git
          cd indi
          git fetch --tags
          git checkout v2.2.2
          mk-build-deps -i -r debian/control -t 'apt-get -y --no-install-recommends'
          pwd
          ls

      - name: Build Indi Package
        run: |
          cd /tmp/indi/indi
          dpkg-buildpackage -us -uc -b

      - name: Package Deb Files
        run: |
          cd /tmp/indi/
          tar -czvf indi.tar.gz indi-bin_*.deb libindi1_*deb libindi-data_*deb libindi-dev_*deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libindi_dev
          path: |
            /tmp/indi/libindi-dev_*deb
            /tmp/indi/libindi1_*deb
            /tmp/indi/libindi-data_*deb
            /tmp/indi/indi-bin_*deb

#      - name: Create Release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ github.ref_name }}
#          files: /tmp/indi/indi.tar.gz

  openphd2:
    needs: indi
    runs-on: ubuntu-24.04-arm

    container:
      image: debian:trixie

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: libindi_dev
          path: .

      - name: Install Dependencies
        run: |
          apt update
          apt install -y build-essential git cmake pkg-config \
              libwxgtk3.2-dev wx-common wx3.2-i18n \
              libnova-dev gettext zlib1g-dev libx11-dev \
              libcurl4-gnutls-dev libopencv-dev libeigen3-dev \
              libgtest-dev

      - name: Install indi Dependency
        run: |
          apt install -y ./indi*deb ./libindi*deb

      - name: Clone openphd2 Repo
        run: git clone --depth 1 https://github.com/OpenPHDGuiding/phd2

      - name: Build env setup
        run: |
          cd phd2
          mkdir -p tmp
          cd tmp
          cmake -DUSE_SYSTEM_LIBINDI=1 ..
          make
          ls


