name: Build newest deb package for aarch64 debian
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04-arm

    container:
      image: debian:trixie

    steps:
      - run: uname -m
      - run: cat /etc/os-release
